import { v4 as uuidv4 } from "uuid";

import { Prompt } from "~/@types";

export const quickAddPrompts: Prompt[] = [
  // Mental Health
  {
    uuid: uuidv4(),
    promptText: "Did you practice any form of self-care today?",
    responseType: "yesno",
    notificationConfig_days: {
      sunday: false,
      monday: true,
      tuesday: false,
      wednesday: false,
      thursday: false,
      friday: false,
      saturday: false,
    },
    notificationConfig_startTime: "09:00",
    notificationConfig_endTime: "17:00",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Mental Health",
      isNotificationActive: true,
    },
  },
  {
    uuid: uuidv4(),
    promptText:
      "On a scale of 1-10, how would you rate your current stress level?",
    responseType: "number",
    notificationConfig_days: {
      sunday: false,
      monday: false,
      tuesday: true,
      wednesday: false,
      thursday: false,
      friday: false,
      saturday: false,
    },
    notificationConfig_startTime: "11:00",
    notificationConfig_endTime: "18:00",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Mental Health",
      isNotificationActive: true,
    },
  },
  {
    uuid: uuidv4(),
    promptText: "Did you practice mindfulness or meditation today?",
    responseType: "yesno",
    notificationConfig_days: {
      sunday: false,
      monday: false,
      tuesday: false,
      wednesday: true,
      thursday: false,
      friday: false,
      saturday: false,
    },
    notificationConfig_startTime: "13:00",
    notificationConfig_endTime: "18:00",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Mental Health",
      isNotificationActive: true,
    },
  },

  // Productivity
  {
    uuid: uuidv4(),
    promptText: "Did you complete your most important task for today?",
    responseType: "yesno",
    notificationConfig_days: {
      sunday: false,
      monday: false,
      tuesday: false,
      wednesday: false,
      thursday: true,
      friday: false,
      saturday: false,
    },
    notificationConfig_startTime: "10:00",
    notificationConfig_endTime: "20:00",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Productivity",
      isNotificationActive: true,
    },
  },
  {
    uuid: uuidv4(),
    promptText:
      "How many pomodoros (25-minute work intervals) did you complete today?",
    responseType: "number",
    notificationConfig_days: {
      sunday: false,
      monday: true,
      tuesday: false,
      wednesday: false,
      thursday: false,
      friday: false,
      saturday: false,
    },
    notificationConfig_startTime: "09:00",
    notificationConfig_endTime: "17:00",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Productivity",
      isNotificationActive: true,
    },
  },
  {
    uuid: uuidv4(),
    promptText: "Did you eliminate any distractions while working today?",
    responseType: "yesno",
    notificationConfig_days: {
      sunday: false,
      monday: false,
      tuesday: true,
      wednesday: false,
      thursday: false,
      friday: false,
      saturday: false,
    },
    notificationConfig_startTime: "11:00",
    notificationConfig_endTime: "18:00",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Productivity",
      isNotificationActive: true,
    },
  },

  // Relationships
  {
    uuid: uuidv4(),
    promptText: "Did you express gratitude to someone today?",
    responseType: "yesno",
    notificationConfig_days: {
      sunday: false,
      monday: false,
      tuesday: false,
      wednesday: true,
      thursday: false,
      friday: false,
      saturday: false,
    },
    notificationConfig_startTime: "13:00",
    notificationConfig_endTime: "18:00",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Relationships",
      isNotificationActive: true,
    },
  },
  {
    uuid: uuidv4(),
    promptText:
      "On a scale of 1-10, how connected do you feel with your loved ones?",
    responseType: "number",
    notificationConfig_days: {
      sunday: false,
      monday: false,
      tuesday: false,
      wednesday: false,
      thursday: true,
      friday: false,
      saturday: false,
    },
    notificationConfig_startTime: "10:00",
    notificationConfig_endTime: "20:00",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Relationships",
      isNotificationActive: true,
    },
  },
  {
    uuid: uuidv4(),
    promptText: "Did you have a meaningful conversation with someone today?",
    responseType: "yesno",
    notificationConfig_days: {
      sunday: false,
      monday: false,
      tuesday: true,
      wednesday: false,
      thursday: false,
      friday: false,
      saturday: false,
    },
    notificationConfig_startTime: "11:00",
    notificationConfig_endTime: "18:00",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Relationships",
      isNotificationActive: true,
    },
  },

  // Health and Fitness
  {
    uuid: uuidv4(),
    promptText: "Did you engage in any physical exercise today?",
    responseType: "yesno",
    notificationConfig_days: {
      sunday: false,
      monday: true,
      tuesday: false,
      wednesday: false,
      thursday: false,
      friday: false,
      saturday: false,
    },
    notificationConfig_startTime: "09:00",
    notificationConfig_endTime: "17:00",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Health and Fitness",
      isNotificationActive: true,
    },
  },
  {
    uuid: uuidv4(),
    promptText:
      "How many servings of fruits and vegetables did you consume today?",
    responseType: "number",
    notificationConfig_days: {
      sunday: false,
      monday: false,
      tuesday: false,
      wednesday: true,
      thursday: false,
      friday: false,
      saturday: false,
    },
    notificationConfig_startTime: "13:00",
    notificationConfig_endTime: "18:00",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Health and Fitness",
      isNotificationActive: true,
    },
  },
  {
    uuid: uuidv4(),
    promptText: "Did you get enough sleep last night?",
    responseType: "yesno",
    notificationConfig_days: {
      sunday: false,
      monday: false,
      tuesday: false,
      wednesday: false,
      thursday: true,
      friday: false,
      saturday: false,
    },
    notificationConfig_startTime: "10:00",
    notificationConfig_endTime: "20:00",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Health and Fitness",
      isNotificationActive: true,
    },
  },

  // Spiritual Practice
  {
    uuid: uuidv4(),
    promptText: "Did you spend time in meditation or prayer today?",
    responseType: "yesno",
    notificationConfig_days: {
      sunday: false,
      monday: false,
      tuesday: false,
      wednesday: false,
      thursday: false,
      friday: true,
      saturday: false,
    },
    notificationConfig_startTime: "09:00",
    notificationConfig_endTime: "17:00",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Spiritual Practice",
      isNotificationActive: true,
    },
  },
  {
    uuid: uuidv4(),
    promptText:
      "On a scale of 1-10, how connected do you feel with your spirituality?",
    responseType: "number",
    notificationConfig_days: {
      sunday: false,
      monday: false,
      tuesday: false,
      wednesday: false,
      thursday: false,
      friday: false,
      saturday: true,
    },
    notificationConfig_startTime: "11:00",
    notificationConfig_endTime: "18:00",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Spiritual Practice",
      isNotificationActive: true,
    },
  },
  {
    uuid: uuidv4(),
    promptText: "Did you engage in any spiritual reading or study today?",
    responseType: "yesno",
    notificationConfig_days: {
      sunday: false,
      monday: false,
      tuesday: false,
      wednesday: false,
      thursday: true,
      friday: false,
      saturday: false,
    },
    notificationConfig_startTime: "13:00",
    notificationConfig_endTime: "18:00",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Spiritual Practice",
      isNotificationActive: true,
    },
  },

  // Personal Interest
  {
    uuid: uuidv4(),
    promptText: "Did you spend time pursuing your hobbies or interests today?",
    responseType: "yesno",
    notificationConfig_days: {
      sunday: false,
      monday: true,
      tuesday: false,
      wednesday: false,
      thursday: false,
      friday: false,
      saturday: false,
    },
    notificationConfig_startTime: "09:00",
    notificationConfig_endTime: "17:00",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Personal Interest",
      isNotificationActive: true,
    },
  },
  {
    uuid: uuidv4(),
    promptText: "How many pages of a book did you read today?",
    responseType: "number",
    notificationConfig_days: {
      sunday: false,
      monday: false,
      tuesday: false,
      wednesday: true,
      thursday: false,
      friday: false,
      saturday: false,
    },
    notificationConfig_startTime: "13:00",
    notificationConfig_endTime: "18:00",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Personal Interest",
      isNotificationActive: true,
    },
  },
  {
    uuid: uuidv4(),
    promptText: "Did you learn something new today?",
    responseType: "yesno",
    notificationConfig_days: {
      sunday: false,
      monday: false,
      tuesday: true,
      wednesday: false,
      thursday: false,
      friday: false,
      saturday: false,
    },
    notificationConfig_startTime: "11:00",
    notificationConfig_endTime: "18:00",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Personal Interest",
      isNotificationActive: true,
    },
  },

  // Other
  {
    uuid: uuidv4(),
    promptText: "Did you take any steps towards achieving your goals today?",
    responseType: "yesno",
    notificationConfig_days: {
      sunday: false,
      monday: false,
      tuesday: false,
      wednesday: true,
      thursday: false,
      friday: false,
      saturday: false,
    },
    notificationConfig_startTime: "13:00",
    notificationConfig_endTime: "18:00",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Other",
      isNotificationActive: true,
    },
  },
  {
    uuid: uuidv4(),
    promptText: "How many new people did you meet today?",
    responseType: "number",
    notificationConfig_days: {
      sunday: false,
      monday: false,
      tuesday: false,
      wednesday: false,
      thursday: true,
      friday: false,
      saturday: false,
    },
    notificationConfig_startTime: "10:00",
    notificationConfig_endTime: "20:00",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Other",
      isNotificationActive: true,
    },
  },
  {
    uuid: uuidv4(),
    promptText: "Did you engage in any creative activities today?",
    responseType: "yesno",
    notificationConfig_days: {
      sunday: false,
      monday: false,
      tuesday: true,
      wednesday: false,
      thursday: false,
      friday: false,
      saturday: false,
    },
    notificationConfig_startTime: "11:00",
    notificationConfig_endTime: "18:00",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Other",
      isNotificationActive: true,
    },
  },
];
