import { v4 as uuidv4 } from "uuid";

import { Prompt } from "~/@types";

export const categories = [
  {
    name: "Mental Health",
    color: "#FFC0CB",
    icon: "🧠",
  },
  {
    name: "Productivity",
    color: "#FFD700",
    icon: "👩‍💻",
  },
  {
    name: "Relationships",
    color: "#00FFFF",
    icon: "👫",
  },
  {
    name: "Health and Fitness",
    color: "#00FF00",
    icon: "🏃",
  },
  {
    name: "Spiritual Practice",
    color: "#FFA500",
    icon: "🧘",
  },
  {
    name: "Self-Care",
    color: "#",
    icon: "🧖",
  },
  {
    name: "Finance",
    color: "#FF0000",
    icon: "💸",
  },
  {
    name: "Personal Interest",
    color: "#800080",
    icon: "🤩",
  },
  {
    name: "Other",
    color: "#000000",
    icon: "📁",
  },
];

export const quickAddPrompts: Prompt[] = [
  // Mental Health
  {
    uuid: uuidv4(),
    promptText: "Did you practice any form of self-care today?",
    responseType: "yesno",
    notificationConfig_days: {
      sunday: false,
      monday: true,
      tuesday: false,
      wednesday: false,
      thursday: false,
      friday: false,
      saturday: false,
    },
    notificationConfig_startTime: "22:00",
    notificationConfig_endTime: "22:02",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Self-Care",
      isNotificationActive: true,
    },
  },
  {
    uuid: uuidv4(),
    promptText:
      "On a scale of 1-10, how would you rate your current stress level?",
    responseType: "number",
    notificationConfig_days: {
      sunday: false,
      monday: true,
      tuesday: true,
      wednesday: false,
      thursday: false,
      friday: true,
      saturday: false,
    },
    notificationConfig_startTime: "11:00",
    notificationConfig_endTime: "22:00",
    notificationConfig_countPerDay: 3,
    additionalMeta: {
      category: "Mental Health",
      isNotificationActive: true,
    },
  },
  {
    uuid: uuidv4(),
    promptText: "How are you, really?",
    responseType: "customOptions",
    notificationConfig_days: {
      sunday: false,
      monday: false,
      tuesday: true,
      wednesday: false,
      thursday: false,
      friday: false,
      saturday: false,
    },
    notificationConfig_startTime: "11:00",
    notificationConfig_endTime: "22:00",
    notificationConfig_countPerDay: 3,
    additionalMeta: {
      category: "Mental Health",
      isNotificationActive: true,
      customOptionText:
        "Hopeful;Neutral;Despair;Energetic;Tired;Happy;Foggy;Manic;Content;Other",
    },
  },

  // Productivity
  {
    uuid: uuidv4(),
    promptText: "What's your most important task for today?",
    responseType: "text",
    notificationConfig_days: {
      sunday: false,
      monday: true,
      tuesday: true,
      wednesday: true,
      thursday: true,
      friday: true,
      saturday: false,
    },
    notificationConfig_startTime: "10:00",
    notificationConfig_endTime: "10:02",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Productivity",
      isNotificationActive: true,
    },
  },
  {
    uuid: uuidv4(),
    promptText: "Did you complete your most important task for today?",
    responseType: "yesno",
    notificationConfig_days: {
      sunday: false,
      monday: true,
      tuesday: true,
      wednesday: true,
      thursday: true,
      friday: true,
      saturday: false,
    },
    notificationConfig_startTime: "22:00",
    notificationConfig_endTime: "22:02",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Productivity",
      isNotificationActive: true,
    },
  },
  {
    uuid: uuidv4(),
    promptText:
      "How many pomodoros (25-minute work intervals) did you complete today?",
    responseType: "number",
    notificationConfig_days: {
      sunday: false,
      monday: true,
      tuesday: false,
      wednesday: false,
      thursday: false,
      friday: false,
      saturday: false,
    },
    notificationConfig_startTime: "22:00",
    notificationConfig_endTime: "22:02",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Productivity",
      isNotificationActive: true,
    },
  },
  {
    uuid: uuidv4(),
    promptText: "How are you eliminating distractions while working today?",
    responseType: "text",
    notificationConfig_days: {
      sunday: false,
      monday: false,
      tuesday: true,
      wednesday: false,
      thursday: false,
      friday: false,
      saturday: false,
    },
    notificationConfig_startTime: "11:00",
    notificationConfig_endTime: "18:00",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Productivity",
      isNotificationActive: true,
    },
  },

  // Relationships
  {
    uuid: uuidv4(),
    promptText: "Did you express gratitude to someone today?",
    responseType: "yesno",
    notificationConfig_days: {
      sunday: false,
      monday: false,
      tuesday: false,
      wednesday: true,
      thursday: false,
      friday: false,
      saturday: false,
    },
    notificationConfig_startTime: "13:00",
    notificationConfig_endTime: "18:00",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Relationships",
      isNotificationActive: true,
    },
  },
  {
    uuid: uuidv4(),
    promptText:
      "On a scale of 1-10, how connected do you feel with your loved ones?",
    responseType: "number",
    notificationConfig_days: {
      sunday: true,
      monday: false,
      tuesday: false,
      wednesday: false,
      thursday: true,
      friday: false,
      saturday: true,
    },
    notificationConfig_startTime: "10:00",
    notificationConfig_endTime: "22:00",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Relationships",
      isNotificationActive: true,
    },
  },
  {
    uuid: uuidv4(),
    promptText: "Did you have a meaningful conversation with someone today?",
    responseType: "yesno",
    notificationConfig_days: {
      sunday: false,
      monday: false,
      tuesday: true,
      wednesday: false,
      thursday: true,
      friday: false,
      saturday: false,
    },
    notificationConfig_startTime: "20:00",
    notificationConfig_endTime: "20:02",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Relationships",
      isNotificationActive: true,
    },
  },

  // Health and Fitness
  {
    uuid: uuidv4(),
    promptText: "Did you engage in any physical exercise today?",
    responseType: "yesno",
    notificationConfig_days: {
      sunday: false,
      monday: true,
      tuesday: false,
      wednesday: false,
      thursday: false,
      friday: false,
      saturday: false,
    },
    notificationConfig_startTime: "17:00",
    notificationConfig_endTime: "17:02",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Health and Fitness",
      isNotificationActive: true,
    },
  },
  {
    uuid: uuidv4(),
    promptText: "Did you have any fruits/vegetables today?",
    responseType: "yesno",
    notificationConfig_days: {
      sunday: false,
      monday: false,
      tuesday: false,
      wednesday: true,
      thursday: false,
      friday: false,
      saturday: false,
    },
    notificationConfig_startTime: "13:00",
    notificationConfig_endTime: "18:00",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Health and Fitness",
      isNotificationActive: true,
    },
  },
  {
    uuid: uuidv4(),
    promptText: "Did you get enough sleep last night?",
    responseType: "yesno",
    notificationConfig_days: {
      sunday: true,
      monday: true,
      tuesday: true,
      wednesday: true,
      thursday: true,
      friday: true,
      saturday: true,
    },
    notificationConfig_startTime: "10:00",
    notificationConfig_endTime: "10:02",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Health and Fitness",
      isNotificationActive: true,
    },
  },

  // Spiritual Practice
  {
    uuid: uuidv4(),
    promptText: "You talked to God?",
    responseType: "yesno",
    notificationConfig_days: {
      sunday: true,
      monday: false,
      tuesday: false,
      wednesday: true,
      thursday: false,
      friday: false,
      saturday: true,
    },
    notificationConfig_startTime: "09:00",
    notificationConfig_endTime: "18:00",
    notificationConfig_countPerDay: 3,
    additionalMeta: {
      category: "Spiritual Practice",
      isNotificationActive: true,
    },
  },
  {
    uuid: uuidv4(),
    promptText: "Did you engage in any spiritual reading or study today?",
    responseType: "yesno",
    notificationConfig_days: {
      sunday: false,
      monday: false,
      tuesday: false,
      wednesday: false,
      thursday: true,
      friday: false,
      saturday: false,
    },
    notificationConfig_startTime: "22:00",
    notificationConfig_endTime: "22:02",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Spiritual Practice",
      isNotificationActive: true,
    },
  },
  {
    uuid: uuidv4(),
    promptText: "Did you practice mindfulness or meditation today?",
    responseType: "yesno",
    notificationConfig_days: {
      sunday: false,
      monday: false,
      tuesday: false,
      wednesday: true,
      thursday: false,
      friday: false,
      saturday: false,
    },
    notificationConfig_startTime: "22:00",
    notificationConfig_endTime: "22:02",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Spiritual Practice",
      isNotificationActive: true,
    },
  },

  // Personal Interest
  {
    uuid: uuidv4(),
    promptText: "Did you spend time pursuing your hobbies or interests today?",
    responseType: "yesno",
    notificationConfig_days: {
      sunday: false,
      monday: true,
      tuesday: false,
      wednesday: true,
      thursday: false,
      friday: true,
      saturday: false,
    },
    notificationConfig_startTime: "22:00",
    notificationConfig_endTime: "22:02",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Personal Interest",
      isNotificationActive: true,
    },
  },
  {
    uuid: uuidv4(),
    promptText: "What are you grateful for today?",
    responseType: "text",
    notificationConfig_days: {
      sunday: false,
      monday: true,
      tuesday: false,
      wednesday: true,
      thursday: false,
      friday: true,
      saturday: true,
    },
    notificationConfig_startTime: "22:00",
    notificationConfig_endTime: "22:02",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Mental Health",
      isNotificationActive: true,
    },
  },
  {
    uuid: uuidv4(),
    promptText: "Did you learn something new today?",
    responseType: "yesno",
    notificationConfig_days: {
      sunday: false,
      monday: false,
      tuesday: true,
      wednesday: false,
      thursday: false,
      friday: false,
      saturday: false,
    },
    notificationConfig_startTime: "22:00",
    notificationConfig_endTime: "22:02",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Personal Interest",
      isNotificationActive: true,
    },
  },

  // Other
  {
    uuid: uuidv4(),
    promptText: "Did you take any steps towards achieving your goals today?",
    responseType: "yesno",
    notificationConfig_days: {
      sunday: false,
      monday: false,
      tuesday: false,
      wednesday: true,
      thursday: false,
      friday: false,
      saturday: false,
    },
    notificationConfig_startTime: "22:00",
    notificationConfig_endTime: "22:02",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Other",
      isNotificationActive: true,
    },
  },
  {
    uuid: uuidv4(),
    promptText: "How many new people did you meet today?",
    responseType: "number",
    notificationConfig_days: {
      sunday: false,
      monday: false,
      tuesday: false,
      wednesday: false,
      thursday: true,
      friday: false,
      saturday: false,
    },
    notificationConfig_startTime: "22:00",
    notificationConfig_endTime: "22:02",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Other",
      isNotificationActive: true,
    },
  },
  {
    uuid: uuidv4(),
    promptText: "Did you engage in any creative activities today?",
    responseType: "yesno",
    notificationConfig_days: {
      sunday: false,
      monday: false,
      tuesday: true,
      wednesday: false,
      thursday: false,
      friday: false,
      saturday: false,
    },
    notificationConfig_startTime: "22:00",
    notificationConfig_endTime: "22:02",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Other",
      isNotificationActive: true,
    },
  },
  // Finance
  {
    uuid: uuidv4(),
    promptText: "Have you reviewed your budget for the week?",
    responseType: "yesno",
    notificationConfig_days: {
      sunday: true,
      monday: false,
      tuesday: false,
      wednesday: false,
      thursday: false,
      friday: false,
      saturday: false,
    },
    notificationConfig_startTime: "22:00",
    notificationConfig_endTime: "22:02",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Finance",
      isNotificationActive: true,
    },
  },
  {
    uuid: uuidv4(),
    promptText: "How are you feeling about money?",
    responseType: "text",
    notificationConfig_days: {
      sunday: false,
      monday: false,
      tuesday: false,
      wednesday: true,
      thursday: false,
      friday: false,
      saturday: true,
    },
    notificationConfig_startTime: "22:00",
    notificationConfig_endTime: "22:02",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Finance",
      isNotificationActive: true,
    },
  },
];

const top_responsders = [
  "npub145mn3p3mq76v05aseprmjq7uwmkjtzjxa393mwg95s3z4mj20jeqhwc2al",
  "npub1h3cu5r79y8erny24jakp7dyr5wmkzjd0swuqm6waa49t8qxq3u3s5rpna7",
  "npub1rlu2lnwgj7vj4v4272f0uwaypwguwv0mw5dlry60c4p9xhqmaglqdh59xy",
  "npub1jvcpwlx3g58558mqr9aeal040lrjqkunmpq5jzgd28dka5ggn99sye2t49",
  "npub1wpkzfdr8ckf97gy749k9azwsvqtdcya4ehacv889v24umdktt7sqzxmwcc",
  "npub15tn7qg24na3ruwj3lsnn0jpv58v33dkg5veyunv22hmpj6ugv83s2a8aqn",
  "npub1xjk22vh8q6u0d78awvav49r6qa0m7m5jfjqm62ea8sdpa5rl7y3ssxq3dh",
  "npub1lxht2r3vkfmk8jy2jacngvp0yvjl5su8ylqvkk2ddqr7vm99w7hsc4drgz",
  "npub1mr4d4pr0sf4jzzmm5fma8hthk76l52q2m78xpu7n2mqs5xxpf55qx0hfhj",
  "npub14xt80f4xe6kgnw2c9h6dmh7mnrp2wkk735sd5397p8e37mapvn8qgce0lf",
  "npub1l73qackxn0salf6mduym4h7vw2l756djjyea4ejree5xygmv5wes5743nh",
  "npub1kysk2akv6jhm2k6w7qgwahkt9kdx4z68fyx0klvc7qucmzwe450s20l8lq",
  "npub1646asy5ffkpn86zc9lds43lwkqt24vecleuwp2aqery9e55y2vns5km3t9",
  "npub1yuj2ts8sarp9ulljamul8ka5gxrr4kf8d0dlc7003ryx6npum96sm6z4d7",
  "npub16ssnj862d9gd0l5dclesqjzq572ptd7xv5wa23qmmk285kmfaeaqvpv2jp",
  "npub15djwdkzyfl38j5fur5hkvgunn722r5kjxtcach9l0slwvvvlehyq8n9fq8",
  "npub1p5slh6nmveh4nn6xdq2jmq9sgy49gyr20ntsrk99usm5d7w4hgyqyykw6q",
  "npub1mnh3y6fa5uw3fqt2260k4y6y3zhusx0kwcqytjhuugehjf7za9zql94yfa",
  "npub1a3aa04lzsr8zxy8nmvnucl2stkpnjl29ralj7c4xm0v5jrq08z4sph56nu",
  "npub1grqwk7nh6v8kgn8x96dshy3wg6dsea2tnmrup4pcleseuer8qm9qalnshd",
  "npub1nfzxqa5uxlrynslzruje04y0wl7kmpu504kpmhjegth4u40297dqdae0a9",
  "npub1pncmz6twkhuurpu9rkzrx6t2kplf0wngkgmjxkxy453gyfms9v3s06xujg",
  "npub1ma33cnqgc7udswspzpzqv70xeu2p6yllt5ynppft09jl68uadysqwjy2dc",
  "npub1h9xw25tn3wd9hyq2hqp4zxpzpqvlkrn0dj4zerp9rl32rzlwd74q83k99g",
  "npub1yh6lqxctg08v4vv25s2pqjgwdfyusfhxg9tvdqhmpgm0xnf8u8ssx450t6",
  "npub1h3565tgklmcfme5q3wwvvzxqnhrcdnqxd0w8khsflnau25lkx0aqx0tc3h",
  "npub135dy9frnc8dfk762q0mpeye5fkkyeyj75sdalehxd4c844w9fk9stwmxf2",
  "npub10kngekxn4gfespz3yj20dj59vj4nwdlhtnlyhrgj2h6v2lcg043q97uunm",
  "npub1qlfcpkedhpv7mx8svgfnyfyeq6nuvv7hzkxrg8evlpsq63yc8xdstlafz4",
  "npub1yphc3se2yag9tx3ydn4cemj2f2scy25359drcvn2a9ne7m0pqw4snnfvyr",
  "npub1elnfj8wh7546ckh5ucy953s6ezkdpxytdmf3ts6avxdfzsntm85s8yk2ed",
  "npub1vc7qpkxxyu5yytnvku73xrcnjylmqw5km68qu83tzsq6dka404nqak85wt",
  "npub1zls36xg0t863cecxh5a495crnas8596uq2j4exwr89dahgftfllss3hq7n",
  "npub1wwuv4qmamyd9vc0p7d755x7rgpd06ztpwajr6j5n80qnsvh8ytqqd7p200",
  "npub1ll3s2kf3c9ytjh0u3caqg3zjc73nc250aqx5287raqgxhxqsyacsud7jzj",
  "npub1jujv2dvqj4c44fprtj5resn2le359sq90mgtahg9zjvvqhxeh4gsrxvm5e",
  "npub18m0hskj52z9try4mfu4cn4y0hg378r6lhwc3xtnqznzvtm4yh9jqfp9x0p",
  "npub1ex00qjzh2a26ndgae6gvurcszamj8aj38qk5gglguy4l2303dlvq2hq4g2",
  "npub1njkqrkgkj5j3u2932tymdd7w0fwakgf05g67sgecj9thm26fk92qe5en4g",
  "npub143eqgzhg5pz4masfz47yfqdcuvyg3qa8m8dqk69mtatph7vns4tsvd7fan",
  "npub1x9xe39mau8mf2quulmktundkswf7yu59qhf2vr7cycp780lxtq4q0l5g4v",
  "npub1axy54dunpektzky85qun6ktvdxxllszvsxaar96jzdn8ktml8m3sjxnkqs",
  "npub1vg67s8ya9fshvjex7mu68fwaqa26guv0fwe5hhs47c8sk0spyqrspwge6a",
  "npub1aj3vkq6we8eqddsgqe5ew5vra3jvx58k4pq32tv7036q6sy37rnseaue7g",
  "npub1hmjd55hkuvdttusjyltw67xauq2xnvh3825nv93crzk53f6cfdvs9vzdqq",
  "npub1d2vreljvkrlypd0lfgzv7gxwejd8zd0egg2pqzqcsvsp9w36kmrs32xdrs",
  "npub1457cp08465e69llg4yra7zvgnvle8rqz7egereafd9np3c8826dqha9f4z",
  "npub1ythjzn9zpawedkf9u6022wcqxpdgtyz5tpvpr4cp4n5tt2u6mzvstkxte7",
  "npub1x2stmme8tfrtv7js344dge44vjcnjjzf3hu93avwqrvn2x5eafeqxzkrhg",
  "npub1c5ezkxmtsf5mumwv3aa3aldej85p0mggq59dhvyst2vkdz7j7xssfgvcvc",
  "npub1waz6ghc2vwzyufucwjauh6ru5gq6fulh3mg73h7ajc7yj7v9mhvqv7elfv",
  "npub1dqrqcd4wymktfyhvtnd3q28lk5udyu3zrl9mmy5l3jjeve9nk35qru50zz",
  "npub13cfgu3pk0uqkhvgh4jju6npvxkwuzvfpkshtleqjd6cgycs49pkskvpm5u",
  "npub1y5sce8qvrwvgeqne57mu5jwalartvatu0w7wcekv05z2rw2ramzqm4amaj",
  "npub1xge0f5tqh0psaev2nhssvg828rwn6c8y8hkhu55k54lzd4s869lq63avhh",
  "npub1kh6rwh8ahjpwyd7fwtse4tzx6a7w2vlvy29qum48hq405l6k9f9qxsxefu",
  "npub1twh439vs67cm2udv9jkw6dsc3fwvm6qsjusrmtxrxs0jx5jc83rq95tz95",
  "npub1the8tywqw06zhsf4gjvrfegnxgfusgy5j3rgechwxdnp08n4szxq8a7nhf",
  "npub1x422fd0xglqca4ts7m80j0zcj8pkev2wnwftp9llhpqxhpyxf9sqjpv78y",
  "npub19wv7fxvdz3y5qpx0ndfymc8f79yxcn8dke5lq0cqpeps59ag9m0qcrkr2c",
  "npub1p97pr0768sfjapdtm499cvvrl0hgkl3t8yp5uv884xf2xgpz5xgqn2qvlf",
  "npub1hy0fnv09dun4ahq82s5a8t72pxvq9pp9873dtr8wlameseu8awlslt9l69",
  "npub1ch0xkyygck6tgskj0rmhtvfsd8cj0ajp468xxvdt8u75xug4qvnqlfsmzf",
  "npub1k6pg6xeyynuh5a5fcs6pp3nmupled950gxl2dwyeh80dwnexqauq97u4k6",
  "npub1r034wkqjy22zfnjx55yl54qmnyvnr0u3t6gjr8gm8frjhhjlvnkqe0agze",
  "npub1jwfkg04gvhm6ldxa64k0v8zrrvajftkqymx29ej00hux26akerdser7zvs",
  "npub1yavwle2ndngrxs3d5uneyyd9wv3kc5rn4j7kaa0xvw5qt0n363xqnuqff6",
  "npub16tt38r6dkfl8m0s96cfrwe7emprtnqq2qssu04zqqflsm42dfftqkqjlew",
  "npub1wz5zkj7l3zs077r9qyerv348cgx6p5mwqydtyrna9ta9rw403m3q4a4xv4",
  "npub1ze50z03qwxu578yqgnrpuex3zsw7wpgve342fkxzq38yrl9cnnjqeez0ft",
  "npub1vmkx0qlzk0upnzqe9f5nx8hlcrusdzsumux6h2dm7dr7gn9nepvq54x52f",
  "npub1c30px6zpgjpug8me5aecagqayums76acel26thc7fyrfedg8uffsx54cpc",
  "npub1a94x43jd0ef8lfugun6u26849qep8fupfsra833fx6f3szyhevhsv9vxek",
  "npub14hj9e2x630847q6fdp04pt0ag3d4f5arhrmasahv36rvs0g9psusxl0u0f",
  "npub1llwu98xfveczssd38q9xv8hygda6s4uh9v4ykp0zg484mavh8cgsaxqptm",
  "npub1z89tczeq4jgfht2fjn44au2dty4e54my77978s07swd0ke6efanqkdt56w",
  "npub1xpkd3tqcykdmfv70rlfahld3zjrn84qzeqn2nnyvwysmf0cuuv0srtrwmv",
  "npub1d6xg5rpj98utmt5atrtygaenkd565jnr2k2j2kx3whpt7klah35qn2r2vf",
  "npub1wmpkzjqry9rxpjv6dg582ezl8wc8laekwphnz00sscc0qmvc4scsv70wfk",
  "npub1gtaph24dskg2yk5sa5khljnlwg3ct3nrdeczpvlzjkhecgylkgys9fyfp4",
  "npub13d66lwk9e0yp2yavj6ksuc5q7xhlkwexp0tmfc865qymx4ynltss6592q5",
  "npub18782qspspzfw4h0627atqkpkjmf2yt0cd2y83an744c6rr62dnhs4rfa6z",
  "npub1m0cynsf2zrz42mpuhq5fzgksakv3qntuz2j27rvf07gcwqeh2utqkuat9y",
  "npub1g5y4f2qegphjq6h3t3884r3mjc7kjcuvmlxcf3dpk38uu9lv6l7qfq93ra",
  "npub1nae0j4jt4qz7frgj7thh088jwg5h2d998g27n48ttwckuc0e5z5q5q3qly",
  "npub1nlwjletgvudpzlrrnjr3d4ckxxmywxdkqhmevgptzusjwhp7v9ks2qfry4",
  "npub124gm0x55lcdz3us6lf58ehnzrvm7ezmgmspml4u7tx5vjh95ajesh3kgvx",
  "npub1az8m47mt80ychewwukx6j8qdjmmmlj0kugn2xynt2vl6v5sq80vs9xksnt",
  "npub1hh7c3t44d5cwfqpnlggewc09vhju8vp5uqwett7qv7j62s7h8myscmwwav",
  "npub1cgzu3qs2me4e2aufq9gx9pqdpv0kxss9zgu0s24e7q3s7x9844uq5quuwg",
  "npub10ahspe8uqfzc3fkafr2g2382gld5jq0er436j0l5z6fxwdy8hvyqqavndn",
  "npub1jt55wes64x6zgj0vvg5lj27mhengqacrvv3p9rnagaulhg4ljm3quyvac0",
  "npub1my8lva2quz59wuwqak9svp6397cqryet5464wr9pkvh340axf64sl2x260",
  "npub13ay0q0yy3r3m7s5w43c6qxlzjusglkgvndpvvs6ljy6yms7akt8se7f0rr",
  "npub19j2lmjapcuz2xj43hyzqpcwk0t907vk2gufsgzch88u758fjdsjsrjzhe4",
  "npub1t6ht4vysetz3958texpsfmswxjpd9vd2jpwh8fhydl9hfwt0p3aqkymk75",
  "npub1appn68zxpcqq7r5dzzhrlh6yys58ldlgzl6m7qclmehaeqg8la3qulsyv3",
  "npub1sykuwwdg9tv57t2v6exkvu0sw9wq4tt5zjs67t287ke36w2ecfkq23qes3",
  "npub13jadpxtymqq85fw7yescqhzdh8fxan7lyncjvgqynutxnh5qmn0slcd4tq",
];
