import { v4 as uuidv4 } from "uuid";

import { Prompt } from "~/@types";

export const categories = [
  {
    name: "Mental Health",
    color: "#FFC0CB",
    icon: "🧠",
  },
  {
    name: "Productivity",
    color: "#FFD700",
    icon: "👩‍💻",
  },
  {
    name: "Relationships",
    color: "#00FFFF",
    icon: "👫",
  },
  {
    name: "Health and Fitness",
    color: "#00FF00",
    icon: "🏃",
  },
  {
    name: "Spiritual Practice",
    color: "#FFA500",
    icon: "🧘",
  },
  {
    name: "Self-Care",
    color: "#",
    icon: "🧖",
  },
  {
    name: "Finance",
    color: "#FF0000",
    icon: "💸",
  },
  {
    name: "Personal Interest",
    color: "#800080",
    icon: "🤩",
  },
  {
    name: "Other",
    color: "#000000",
    icon: "📁",
  },
];

export const quickAddPrompts: Prompt[] = [
  // Mental Health
  {
    uuid: uuidv4(),
    promptText: "Did you practice any form of self-care today?",
    responseType: "yesno",
    notificationConfig_days: {
      sunday: false,
      monday: true,
      tuesday: false,
      wednesday: false,
      thursday: false,
      friday: false,
      saturday: false,
    },
    notificationConfig_startTime: "22:00",
    notificationConfig_endTime: "22:02",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Self-Care",
      isNotificationActive: true,
    },
  },
  {
    uuid: uuidv4(),
    promptText:
      "On a scale of 1-10, how would you rate your current stress level?",
    responseType: "number",
    notificationConfig_days: {
      sunday: false,
      monday: true,
      tuesday: true,
      wednesday: false,
      thursday: false,
      friday: true,
      saturday: false,
    },
    notificationConfig_startTime: "11:00",
    notificationConfig_endTime: "22:00",
    notificationConfig_countPerDay: 3,
    additionalMeta: {
      category: "Mental Health",
      isNotificationActive: true,
    },
  },
  {
    uuid: uuidv4(),
    promptText: "How are you, really?",
    responseType: "customOptions",
    notificationConfig_days: {
      sunday: false,
      monday: false,
      tuesday: true,
      wednesday: false,
      thursday: false,
      friday: false,
      saturday: false,
    },
    notificationConfig_startTime: "11:00",
    notificationConfig_endTime: "22:00",
    notificationConfig_countPerDay: 3,
    additionalMeta: {
      category: "Mental Health",
      isNotificationActive: true,
      customOptionText:
        "Hopeful;Neutral;Despair;Energetic;Tired;Happy;Foggy;Manic;Content;Other",
    },
  },

  // Productivity
  {
    uuid: uuidv4(),
    promptText: "What's your most important task for today?",
    responseType: "text",
    notificationConfig_days: {
      sunday: false,
      monday: true,
      tuesday: true,
      wednesday: true,
      thursday: true,
      friday: true,
      saturday: false,
    },
    notificationConfig_startTime: "10:00",
    notificationConfig_endTime: "10:02",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Productivity",
      isNotificationActive: true,
    },
  },
  {
    uuid: uuidv4(),
    promptText: "Did you complete your most important task for today?",
    responseType: "yesno",
    notificationConfig_days: {
      sunday: false,
      monday: true,
      tuesday: true,
      wednesday: true,
      thursday: true,
      friday: true,
      saturday: false,
    },
    notificationConfig_startTime: "22:00",
    notificationConfig_endTime: "22:02",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Productivity",
      isNotificationActive: true,
    },
  },
  {
    uuid: uuidv4(),
    promptText:
      "How many pomodoros (25-minute work intervals) did you complete today?",
    responseType: "number",
    notificationConfig_days: {
      sunday: false,
      monday: true,
      tuesday: false,
      wednesday: false,
      thursday: false,
      friday: false,
      saturday: false,
    },
    notificationConfig_startTime: "22:00",
    notificationConfig_endTime: "22:02",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Productivity",
      isNotificationActive: true,
    },
  },
  {
    uuid: uuidv4(),
    promptText: "How are you eliminating distractions while working today?",
    responseType: "text",
    notificationConfig_days: {
      sunday: false,
      monday: false,
      tuesday: true,
      wednesday: false,
      thursday: false,
      friday: false,
      saturday: false,
    },
    notificationConfig_startTime: "11:00",
    notificationConfig_endTime: "18:00",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Productivity",
      isNotificationActive: true,
    },
  },

  // Relationships
  {
    uuid: uuidv4(),
    promptText: "Did you express gratitude to someone today?",
    responseType: "yesno",
    notificationConfig_days: {
      sunday: false,
      monday: false,
      tuesday: false,
      wednesday: true,
      thursday: false,
      friday: false,
      saturday: false,
    },
    notificationConfig_startTime: "13:00",
    notificationConfig_endTime: "18:00",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Relationships",
      isNotificationActive: true,
    },
  },
  {
    uuid: uuidv4(),
    promptText:
      "On a scale of 1-10, how connected do you feel with your loved ones?",
    responseType: "number",
    notificationConfig_days: {
      sunday: true,
      monday: false,
      tuesday: false,
      wednesday: false,
      thursday: true,
      friday: false,
      saturday: true,
    },
    notificationConfig_startTime: "10:00",
    notificationConfig_endTime: "22:00",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Relationships",
      isNotificationActive: true,
    },
  },
  {
    uuid: uuidv4(),
    promptText: "Did you have a meaningful conversation with someone today?",
    responseType: "yesno",
    notificationConfig_days: {
      sunday: false,
      monday: false,
      tuesday: true,
      wednesday: false,
      thursday: true,
      friday: false,
      saturday: false,
    },
    notificationConfig_startTime: "20:00",
    notificationConfig_endTime: "20:02",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Relationships",
      isNotificationActive: true,
    },
  },

  // Health and Fitness
  {
    uuid: uuidv4(),
    promptText: "Did you engage in any physical exercise today?",
    responseType: "yesno",
    notificationConfig_days: {
      sunday: false,
      monday: true,
      tuesday: false,
      wednesday: false,
      thursday: false,
      friday: false,
      saturday: false,
    },
    notificationConfig_startTime: "17:00",
    notificationConfig_endTime: "17:02",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Health and Fitness",
      isNotificationActive: true,
    },
  },
  {
    uuid: uuidv4(),
    promptText: "Did you have any fruits/vegetables today?",
    responseType: "yesno",
    notificationConfig_days: {
      sunday: false,
      monday: false,
      tuesday: false,
      wednesday: true,
      thursday: false,
      friday: false,
      saturday: false,
    },
    notificationConfig_startTime: "13:00",
    notificationConfig_endTime: "18:00",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Health and Fitness",
      isNotificationActive: true,
    },
  },
  {
    uuid: uuidv4(),
    promptText: "Did you get enough sleep last night?",
    responseType: "yesno",
    notificationConfig_days: {
      sunday: true,
      monday: true,
      tuesday: true,
      wednesday: true,
      thursday: true,
      friday: true,
      saturday: true,
    },
    notificationConfig_startTime: "10:00",
    notificationConfig_endTime: "10:02",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Health and Fitness",
      isNotificationActive: true,
    },
  },

  // Spiritual Practice
  {
    uuid: uuidv4(),
    promptText: "You talked to God?",
    responseType: "yesno",
    notificationConfig_days: {
      sunday: true,
      monday: false,
      tuesday: false,
      wednesday: true,
      thursday: false,
      friday: false,
      saturday: true,
    },
    notificationConfig_startTime: "09:00",
    notificationConfig_endTime: "18:00",
    notificationConfig_countPerDay: 3,
    additionalMeta: {
      category: "Spiritual Practice",
      isNotificationActive: true,
    },
  },
  {
    uuid: uuidv4(),
    promptText: "Did you engage in any spiritual reading or study today?",
    responseType: "yesno",
    notificationConfig_days: {
      sunday: false,
      monday: false,
      tuesday: false,
      wednesday: false,
      thursday: true,
      friday: false,
      saturday: false,
    },
    notificationConfig_startTime: "22:00",
    notificationConfig_endTime: "22:02",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Spiritual Practice",
      isNotificationActive: true,
    },
  },
  {
    uuid: uuidv4(),
    promptText: "Did you practice mindfulness or meditation today?",
    responseType: "yesno",
    notificationConfig_days: {
      sunday: false,
      monday: false,
      tuesday: false,
      wednesday: true,
      thursday: false,
      friday: false,
      saturday: false,
    },
    notificationConfig_startTime: "22:00",
    notificationConfig_endTime: "22:02",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Spiritual Practice",
      isNotificationActive: true,
    },
  },

  // Personal Interest
  {
    uuid: uuidv4(),
    promptText: "Did you spend time pursuing your hobbies or interests today?",
    responseType: "yesno",
    notificationConfig_days: {
      sunday: false,
      monday: true,
      tuesday: false,
      wednesday: true,
      thursday: false,
      friday: true,
      saturday: false,
    },
    notificationConfig_startTime: "22:00",
    notificationConfig_endTime: "22:02",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Personal Interest",
      isNotificationActive: true,
    },
  },
  {
    uuid: uuidv4(),
    promptText: "What are you grateful for today?",
    responseType: "text",
    notificationConfig_days: {
      sunday: false,
      monday: true,
      tuesday: false,
      wednesday: true,
      thursday: false,
      friday: true,
      saturday: true,
    },
    notificationConfig_startTime: "22:00",
    notificationConfig_endTime: "22:02",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Mental Health",
      isNotificationActive: true,
    },
  },
  {
    uuid: uuidv4(),
    promptText: "Did you learn something new today?",
    responseType: "yesno",
    notificationConfig_days: {
      sunday: false,
      monday: false,
      tuesday: true,
      wednesday: false,
      thursday: false,
      friday: false,
      saturday: false,
    },
    notificationConfig_startTime: "22:00",
    notificationConfig_endTime: "22:02",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Personal Interest",
      isNotificationActive: true,
    },
  },

  // Other
  {
    uuid: uuidv4(),
    promptText: "Did you take any steps towards achieving your goals today?",
    responseType: "yesno",
    notificationConfig_days: {
      sunday: false,
      monday: false,
      tuesday: false,
      wednesday: true,
      thursday: false,
      friday: false,
      saturday: false,
    },
    notificationConfig_startTime: "22:00",
    notificationConfig_endTime: "22:02",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Other",
      isNotificationActive: true,
    },
  },
  {
    uuid: uuidv4(),
    promptText: "How many new people did you meet today?",
    responseType: "number",
    notificationConfig_days: {
      sunday: false,
      monday: false,
      tuesday: false,
      wednesday: false,
      thursday: true,
      friday: false,
      saturday: false,
    },
    notificationConfig_startTime: "22:00",
    notificationConfig_endTime: "22:02",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Other",
      isNotificationActive: true,
    },
  },
  {
    uuid: uuidv4(),
    promptText: "Did you engage in any creative activities today?",
    responseType: "yesno",
    notificationConfig_days: {
      sunday: false,
      monday: false,
      tuesday: true,
      wednesday: false,
      thursday: false,
      friday: false,
      saturday: false,
    },
    notificationConfig_startTime: "22:00",
    notificationConfig_endTime: "22:02",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Other",
      isNotificationActive: true,
    },
  },
  // Finance
  {
    uuid: uuidv4(),
    promptText: "Have you reviewed your budget for the week?",
    responseType: "yesno",
    notificationConfig_days: {
      sunday: true,
      monday: false,
      tuesday: false,
      wednesday: false,
      thursday: false,
      friday: false,
      saturday: false,
    },
    notificationConfig_startTime: "22:00",
    notificationConfig_endTime: "22:02",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Finance",
      isNotificationActive: true,
    },
  },
  {
    uuid: uuidv4(),
    promptText: "How are you feeling about money?",
    responseType: "text",
    notificationConfig_days: {
      sunday: false,
      monday: false,
      tuesday: false,
      wednesday: true,
      thursday: false,
      friday: false,
      saturday: true,
    },
    notificationConfig_startTime: "22:00",
    notificationConfig_endTime: "22:02",
    notificationConfig_countPerDay: 1,
    additionalMeta: {
      category: "Finance",
      isNotificationActive: true,
    },
  },
];

export const top_responders = [
  "npub1yuj2ts8sarp9ulljamul8ka5gxrr4kf8d0dlc7003ryx6npum96sm6z4d7",
  "npub15tn7qg24na3ruwj3lsnn0jpv58v33dkg5veyunv22hmpj6ugv83s2a8aqn",
  "npub1sr4zz522qhmh27tqzkgu2ur2us8xwm4z3s0ghvzn8xmpe6uqcmxszdcaan",
  "npub1h3cu5r79y8erny24jakp7dyr5wmkzjd0swuqm6waa49t8qxq3u3s5rpna7",
  "npub1elnfj8wh7546ckh5ucy953s6ezkdpxytdmf3ts6avxdfzsntm85s8yk2ed",
  "npub1p5slh6nmveh4nn6xdq2jmq9sgy49gyr20ntsrk99usm5d7w4hgyqyykw6q",
  "npub1lxht2r3vkfmk8jy2jacngvp0yvjl5su8ylqvkk2ddqr7vm99w7hsc4drgz",
  "npub1ex00qjzh2a26ndgae6gvurcszamj8aj38qk5gglguy4l2303dlvq2hq4g2",
  "npub1grqwk7nh6v8kgn8x96dshy3wg6dsea2tnmrup4pcleseuer8qm9qalnshd",
  "npub1l73qackxn0salf6mduym4h7vw2l756djjyea4ejree5xygmv5wes5743nh",
  "npub17aqy2gq7tmn33dzdjcemwf8de0rjxl5huawcwttdtsrajrhsw9kscxk95g",
  "npub190kadmevar4jkfgsd9ta256q3yxqlmkt0fn065l7tkc2nmth3umsvkvgxf",
  "npub1kysk2akv6jhm2k6w7qgwahkt9kdx4z68fyx0klvc7qucmzwe450s20l8lq",
  "npub10kngekxn4gfespz3yj20dj59vj4nwdlhtnlyhrgj2h6v2lcg043q97uunm",
  "npub14xt80f4xe6kgnw2c9h6dmh7mnrp2wkk735sd5397p8e37mapvn8qgce0lf",
  "npub1nfzxqa5uxlrynslzruje04y0wl7kmpu504kpmhjegth4u40297dqdae0a9",
  "npub1wpkzfdr8ckf97gy749k9azwsvqtdcya4ehacv889v24umdktt7sqzxmwcc",
  "npub145mn3p3mq76v05aseprmjq7uwmkjtzjxa393mwg95s3z4mj20jeqhwc2al",
  "npub10n5e0q2wtlu8933h9l3ns0xp3a7k672jg3yfmmz6l8w3dwm2hqgsfweczc",
  "npub15djwdkzyfl38j5fur5hkvgunn722r5kjxtcach9l0slwvvvlehyq8n9fq8",
  "npub1wwuv4qmamyd9vc0p7d755x7rgpd06ztpwajr6j5n80qnsvh8ytqqd7p200",
  "npub1834h8gkk3km7ppxn6e3hftgmm88eq787dyfwc22mgaq04m33xylsc7f2mv",
  "npub1hmj7frdfqk0qtksd2k6ucxgfdw265w96n3fgdu94sd6dtflyjvdswgng74",
  "npub1pncmz6twkhuurpu9rkzrx6t2kplf0wngkgmjxkxy453gyfms9v3s06xujg",
  "npub1epkec0xcv3v3sr0es4dwkaxp54hak0tv8ljvuu5l23qgpt0hpc8s5u3ar7",
  "npub1yre089c6ty5rhgl99d4qwp9efunrwvgxskgwjhzv3rp9j6e0cs0qjjgr5e",
  "npub1xjk22vh8q6u0d78awvav49r6qa0m7m5jfjqm62ea8sdpa5rl7y3ssxq3dh",
  "npub1cpp8n3h6vlqpdkx3kvgauwqjn3qt098wfvvpa9xkyekh9plcdf0sa9mn9l",
  "npub15z7szlr429d2305q0zjnm2f96q6z4kvsas5m38p0zetwv4nkumdqn3hahl",
  "npub1w83k6w83f8s3nqt9hrgsxn24460su35senvgqeps0u43flcl389srwfj65",
  "npub16ssnj862d9gd0l5dclesqjzq572ptd7xv5wa23qmmk285kmfaeaqvpv2jp",
  "npub1646asy5ffkpn86zc9lds43lwkqt24vecleuwp2aqery9e55y2vns5km3t9",
  "npub1yphc3se2yag9tx3ydn4cemj2f2scy25359drcvn2a9ne7m0pqw4snnfvyr",
  "npub1jvcpwlx3g58558mqr9aeal040lrjqkunmpq5jzgd28dka5ggn99sye2t49",
  "npub1rlu2lnwgj7vj4v4272f0uwaypwguwv0mw5dlry60c4p9xhqmaglqdh59xy",
  "npub1mnh3y6fa5uw3fqt2260k4y6y3zhusx0kwcqytjhuugehjf7za9zql94yfa",
  "npub14enmf40zkkr8p30pkmhazj9j2zdvjulwf9wuq54q6jfyx470naaqldn2am",
  "npub1mr4d4pr0sf4jzzmm5fma8hthk76l52q2m78xpu7n2mqs5xxpf55qx0hfhj",
  "npub135dy9frnc8dfk762q0mpeye5fkkyeyj75sdalehxd4c844w9fk9stwmxf2",
  "npub1yh6lqxctg08v4vv25s2pqjgwdfyusfhxg9tvdqhmpgm0xnf8u8ssx450t6",
  "npub1twh439vs67cm2udv9jkw6dsc3fwvm6qsjusrmtxrxs0jx5jc83rq95tz95",
  "npub1hgj438pdv9l3yq474g2lerxjvkn4ecyuy7t0qlr6jskw7hjudqeqtq28gc",
  "npub1axy54dunpektzky85qun6ktvdxxllszvsxaar96jzdn8ktml8m3sjxnkqs",
  "npub1ma33cnqgc7udswspzpzqv70xeu2p6yllt5ynppft09jl68uadysqwjy2dc",
  "npub1aj3vkq6we8eqddsgqe5ew5vra3jvx58k4pq32tv7036q6sy37rnseaue7g",
  "npub1h9xw25tn3wd9hyq2hqp4zxpzpqvlkrn0dj4zerp9rl32rzlwd74q83k99g",
  "npub1p97pr0768sfjapdtm499cvvrl0hgkl3t8yp5uv884xf2xgpz5xgqn2qvlf",
  "npub1a3aa04lzsr8zxy8nmvnucl2stkpnjl29ralj7c4xm0v5jrq08z4sph56nu",
  "npub1wr6jvuqcyjxpvtkag8fvclanqdev0qmrhj8unqhau4tc5c42vy3q2j0ql5",
  "npub1h3565tgklmcfme5q3wwvvzxqnhrcdnqxd0w8khsflnau25lkx0aqx0tc3h",
  "npub1g3ah4c6gkmhq8z37ykurhnke7ftqjtpxp3z39vq4gvegsv3xmensngjkew",
  "npub1jujv2dvqj4c44fprtj5resn2le359sq90mgtahg9zjvvqhxeh4gsrxvm5e",
  "npub18m0hskj52z9try4mfu4cn4y0hg378r6lhwc3xtnqznzvtm4yh9jqfp9x0p",
  "npub1x9xe39mau8mf2quulmktundkswf7yu59qhf2vr7cycp780lxtq4q0l5g4v",
  "npub159hraspvas07kq2az4tflcynu0wnfgc9j2nq75fygdqpeqwh0guqxjxzsr",
  "npub143eqgzhg5pz4masfz47yfqdcuvyg3qa8m8dqk69mtatph7vns4tsvd7fan",
];
